fix(child/fault): set fault timestamp in all possible places
openebs/mayastor pull request #1340
Opened 2023-03-26 17:25 UTC by dsharma-dc

It would be ideal to set the timestamp from within set_state(), however that would required mutability changes for `self` in function parameters, which may propagate up. So simply setting the timestamp wherever we are currently setting child state as Faulted.

2023-03-27 10:06 UTC, tiagolobocastro commented
> It would be ideal to set the timestamp from within set_state(), however that would required mutability changes for `self` in function parameters, which may propagate up. So simply setting the timestamp wherever we are currently setting child state as Faulted.

Can we change mutability of `set_state` ? Or have some sort of a fault wrapper?

2023-03-27 10:07 UTC, dsavitskiy commented
@dsharma-dc I see your point about &self mutability in set_state. Still, a much better design decision would be to set "fault_at" in set_state, as otherwise it is very error prone.

You don't actually have to change &self to mut in set_state().

You can change "faulted_at" to be AtomicU64 (like "state" and "prev_state"), and store time since epoch there. To access it in form of Option<DateTime>, add an accessor method "get_fault_at()" that would convert u64 to Option<DateTime>.
You can use one the following conventions:
- faulted_at == 0 means None, and > 0 Some(DateTime).
- check if state is Faulted and if not , return None, otherwise Some(DateTime)

2023-03-27 10:07 UTC, dsavitskiy commented
> > It would be ideal to set the timestamp from within set_state(), however that would required mutability changes for `self` in function parameters, which may propagate up. So simply setting the timestamp wherever we are currently setting child state as Faulted.
> 
> Can we change mutability of `set_state` ? Or have some sort of a fault wrapper?

We don't need to change to &mut, see my comment above.

2023-03-27 10:08 UTC, dsavitskiy requested changes
Please move setting fault_at to set_state().

2023-03-28 06:21 UTC, dsharma-dc commented
Testing:

```

NAME                                                    STATE   REASON    LAST_FAULTED_AT     
bdev:///repl1?uuid=da778218-7591-40ea-95fd-c891f8591c89 online  -         -                   
bdev:///repl2?uuid=5d271c87-42cc-46ff-8d34-18aa052d5cb2 faulted by client 2023-03-28T06:07:42Z

Removed bdev:///repl2?uuid=5d271c87-42cc-46ff-8d34-18aa052d5cb2 from specified nexus
f1350be1-75c4-40dd-90e5-a20bffcb619d
NAME                                                    STATE    REASON      LAST_FAULTED_AT
bdev:///repl1?uuid=da778218-7591-40ea-95fd-c891f8591c89 online   -           -              
bdev:///repl2?uuid=5d271c87-42cc-46ff-8d34-18aa052d5cb2 degraded out of sync -  
```

2023-03-28 09:50 UTC, dsavitskiy requested changes
Please rebase on develop and squash your commits into single one before merging.

2023-03-28 09:50 UTC, dsavitskiy commented on io-engine/src/bdev/nexus/nexus_child.rs
> +                Ordering::Relaxed,
It makes to use AcqRel instead of Relaxed.

2023-03-28 09:50 UTC, dsavitskiy commented on io-engine/src/bdev/nexus/nexus_child.rs
> +            let ts = self.faulted_at.load(Ordering::Relaxed);
Why loading two times?

2023-03-28 09:50 UTC, dsavitskiy commented on io-engine/src/bdev/nexus/nexus_child.rs
> +        if self.faulted_at.load(Ordering::Relaxed) == 0 {
It makes to use AcqRel instead of Relaxed.

2023-03-28 09:57 UTC, dsharma-dc commented on io-engine/src/bdev/nexus/nexus_child.rs
> +            let ts = self.faulted_at.load(Ordering::Relaxed);
Looks redundant yes, changing to this:

 ```
   pub fn fault_timestamp(&self) -> Option<DateTime<Utc>> {
        let ts = self.faulted_at.load(Ordering::Relaxed);
        if ts == 0 {
            None
        }
        NaiveDateTime::from_timestamp_opt(ts as i64, 0)
            .map(|d| DateTime::from_utc(d, Utc))
    }
```

2023-03-28 10:05 UTC, tiagolobocastro commented
> @dsharma-dc I see your point about &self mutability in set_state. Still, a much better design decision would be to set "fault_at" in set_state, as otherwise it is very error prone.
> 
> You don't actually have to change &self to mut in set_state().
> 
> You can change "faulted_at" to be AtomicU64 (like "state" and "prev_state"), and store time since epoch there. To access it in form of Option, add an accessor method "get_fault_at()" that would convert u64 to Option. You can use one the following conventions:
> 
>     * faulted_at == 0 means None, and > 0 Some(DateTime).
> 
>     * check if state is Faulted and if not , return None, otherwise Some(DateTime)

A downside of this is that the timestamp does not fit into 64bits so we'll loose resolution.

2023-03-28 10:34 UTC, dsharma-dc commented
Something wrong happened with the rebase and unnecessary commits are showing up in this PR.  :( 
Fixing that.

2023-03-28 11:47 UTC, closed without merging