Run CSI e2e tests in CI/CD pipeline CAS-577
openebs/Mayastor pull request #594
Opened 2020-12-18 15:38 UTC by blaisedias

Refactor scripts/e2e-test.sh to
 * Run the CSI tests
 * Be more developer friendly

1. Add csi to the set of tests run by default
2. The set of tests to be run can now be specified
   using env var e2e_tests
3. Run uninstall test only if specified,
    and always after all other tests have
    run successfully or not.

2020-12-22 17:43 UTC, arne-rusek commented
This seem to be conflicting with https://github.com/openebs/Mayastor/pull/597/

Let's discuss on slack what to do as it seems they're doing both very similar things.

2020-12-22 17:44 UTC, arne-rusek requested changes
This seem to be conflicting with https://github.com/openebs/Mayastor/pull/597/

Let's discuss on slack what to do as it seems they're doing both very similar things.

2020-12-23 22:17 UTC, jkryl commented
I like:
* being able to specify what tests to run
* having shell script function to run a test so we don't need to repeat the same parameters everywhere
what I don't like that much is:
* introducing new env variables instead of command line options - confusing if the tool is configured using both ways
* quite complicated logic iterating over tests skipping uninstall and then iterating again running only uninstall - we could have simply just a list of tests to run

but as Arne suggested it's probably better to discuss that in the chat after the e2e nightly PR is merged.

2021-01-04 13:20 UTC, blaisedias commented
bors try

2021-01-05 09:38 UTC, blaisedias commented
Superseded by https://github.com/openebs/Mayastor/pull/595

2021-01-05 09:38 UTC, closed without merging