test: ensure deletion of objects timed out during creation.
openebs/Mayastor pull request #634
Opened 2021-01-15 14:18 UTC by chriswldenyer

Remove test storage class unconditionally.
Ensure pod remove test runs on a 3 node cluster.

2021-01-15 14:23 UTC, chriswldenyer commented
bors try

2021-01-15 15:04 UTC, paulyoong approved these changes

2021-01-18 07:04 UTC, chriswldenyer commented
bors try

2021-01-18 11:19 UTC, arne-rusek requested changes

2021-01-18 13:22 UTC, chriswldenyer commented on test/e2e/node_disconnect/lib/node_disconnect_lib.go
> +	Expect(len(env.otherNodes)).To(BeNumerically("==", 2)) // must run on a 3 node cluster
It could be done. I'll have a look.

2021-01-20 08:52 UTC, closed without merging

2021-01-20 08:52 UTC, chriswldenyer commented
Wii re-open as new PR because there are a lot of new changes.