test: send xray reports
openebs/Mayastor pull request #683
Opened 2021-02-08 11:51 UTC by chriswldenyer

Send reports to Jira xray. Specify which test spec in the
Jenkinsfile. Currently implemented for on-demand E2E tests.

2021-02-08 14:11 UTC, chriswldenyer commented
bors try

2021-02-08 16:25 UTC, chriswldenyer commented
bors try

2021-02-09 09:22 UTC, chriswldenyer commented
bors try

2021-02-09 10:51 UTC, chriswldenyer commented
bors try

2021-02-09 14:11 UTC, closed without merging

2021-02-09 14:12 UTC, chriswldenyer commented
Should add Jenkins Junit reporting as well.

2021-02-09 14:12 UTC, blaisedias requested changes

2021-02-09 14:12 UTC, blaisedias commented on scripts/e2e-test.sh
> +echo "    test_plan=$test_plan_arg"
The unofficial convention is environment variables used to control go code behaviour, are prefixed with e2e_