test(e2e): run fio continuously in pod remove
openebs/Mayastor pull request #817
Opened 2021-03-29 14:49 UTC by chriswldenyer

Run fio continuously while pod-loss-induced rebuild tests occur.
Halt fio remotely using the --trigger-file option.

To do: remove the replica hosted on the nexus.

2021-03-29 15:17 UTC, chriswldenyer commented
bors try

2021-03-29 15:33 UTC, blaisedias requested changes

2021-03-29 15:42 UTC, chriswldenyer commented on test/e2e/ms_pod_disruption/disruption_lib.go
> +		time.Sleep(5 * time.Second)
Will remove this sleep and the one below. Not sure where they came from.

2021-03-29 15:42 UTC, chriswldenyer commented on test/e2e/ms_pod_disruption/disruption_lib.go
> +	image := "mayadata/e2e-fio"
Ok, will fix.

2021-03-29 15:59 UTC, chriswldenyer commented on test/e2e/ms_pod_disruption/disruption_lib.go
> +		time.Sleep(5 * time.Second)
fixed

2021-03-29 15:59 UTC, chriswldenyer commented on test/e2e/ms_pod_disruption/disruption_lib.go
> +	image := "mayadata/e2e-fio"
fixed

2021-03-29 15:59 UTC, chriswldenyer commented on test/e2e/ms_pod_disruption/disruption_lib.go
> +		time.Sleep(5 * time.Second)
fixed

2021-04-14 09:35 UTC, tiagolobocastro commented
@chriswldenyer this should be closed on this repo now?

2021-04-14 13:16 UTC, chriswldenyer commented
> @chriswldenyer this should be closed on this repo now?

yes, you are right, closing now,

2021-04-14 13:16 UTC, closed without merging